#Makefile do projeto
all:
	gcc player.c interface.c utils.c binFile.c main.c -o main -g -march=native
run:
	./main
clean:
	rm main
zip:
	zip Trabalho_Introdutorio_14569373_1467810.zip *.c *.h Makefile README.txt